### ISSUE TITLE
the screen kept changing

### ISSUE THREAD

**Issue by independent-coder** [Eiim/Chokistream#15]
![Screenshot_5](https://user-images.githubusercontent.com/127637860/236571450-283d5c44-e738-492b-83c9-8015c5a62ad2.png)
![Screenshot_4](https://user-images.githubusercontent.com/127637860/236571341-f53a3ee1-e51f-445a-899c-bab73a67ea4e.png)
and ofset pls help me !

**Comment by Eiim** [comment]
Which version of HzMod are you using, and which game is that? Is "Request TGA" checked in the mod options? (if so, this is #5 and switching off that mode should fix it).

**Comment by tyrie592** [comment]
I have this exact same issue, and unticking "Request TGA" doesn't seem to fix it.

**Comment by Eiim** [comment]
Good to know. Do you know which game and HzMod version? I'll plan to investigate this week.

**Comment by Eiim** [comment]
I just realized this is in the main menu, obvious in retrospect from the screenshot but would have been nice to know. The main menu is known to be generally buggier than games, but it still ought to work, and works for me in all the ([supported](https://github.com/Eiim/Chokistream/wiki/HzMod-Support-Comparison)) configurations I've tried. Make sure you're on [v1.1](https://github.com/Eiim/Chokistream/releases/tag/v1.1) of Chokistream, and if so, let me know:
* Which version of HzMod you're using and/or where you got it from
* Which console you have (very likely one of 3DS, 3DS XL, New 3DS, New 3DS XL, 2DS (does HzMod even work on 2DS?), or 2DS XL)
* Set Log Level to Extreme and Log Mode to File, recreate the issue (briefly! after a second or so you can quit Chokistream, because Extreme logs get big fast), and send me the log file. There's no sensitive data here, but it's effectively a complete copy of the communication between your computer and the 3DS, so I can manually sift through it to find any discrepancies.

**Comment by tyrie592** [comment]
I got my version of HzMod from here: 
https://www.gamebrew.org/wiki/HzMod_3DS

The file says last modified 2018, so I think its the 2018 version. For me this is running on an Old 3DS XL. I'll put the log file here tomorrow.

**Comment by Eiim** [comment]
Yeah, that's the 2018-02-04 version. It's probably an Old 3DS-specific bug then. #8 is probably related (although on N3DS top screen works while bottom doesn't), I'll need to do some testing regarding that. The log file would be quite useful when you get it.

**Comment by Eiim** [comment]
Fixed in #16

**Comment by Eiim** [comment]
And now released in [1.2](https://github.com/Eiim/Chokistream/releases/tag/v1.2)!
